---
#- import_tasks: sg_rule_icmp.yml
# tasks file for sg_provsioning
- os_security_group:
    cloud: ospcloud
    state: present
    name: sg_apps
    description: SG for APPS servers

- os_security_group_rule:
    cloud: ospcloud
    security_group: sg_apps
    protocol: tcp
    port_range_min: "{{ item.port }}"
    port_range_max: "{{ item.port }}"
    remote_ip_prefix: "{{ item.ip_prefix }}"
  loop:
    - { port: '8080' , ip_prefix: '0.0.0.0/0' }
    - { port: '22' , ip_prefix: '0.0.0.0/0' }
  register: result

- name: what's the ports ?
  debug: 
    var: result

#- os_sercurity_group_rule:
#    cloud: ospcloud
#    security_group: sg_apps
#    protocol: icmp
#    port_range_min: -1
#    port_range_max: -1
#    remote_ip_prefix: 0.0.0.0/0
- os_security_group:
    cloud: ospcloud
    state: present
    name: sg_fe
    description: SG for FRENTEND servers
- os_security_group_rule:
    cloud: ospcloud
    security_group: sg_fe
    protocol: tcp
    port_range_min: "{{item.port}}"
    port_range_max: "{{item.port}}"
    remote_ip_prefix: "{{item.ip_prefix}}"
  loop:
    - { port: '80' , ip_prefix: '0.0.0.0/0' }
    - { port: '433' , ip_prefix: '0.0.0.0/0' }
    - { port: '22' , ip_prefix: '0.0.0.0/0' }

- os_security_group:
    cloud: ospcloud
    state: present
    name: sg_db
    description: SG for DB servers

- os_security_group_rule:
    cloud: ospcloud
    security_group: sg_db
    protocol: tcp
    port_range_min: "{{item.port}}"
    port_range_max: "{{item.port}}"
    remote_ip_prefix: "{{item.ip_prefix}}"
  loop:
    - { port: '5432' , ip_prefix: '20.20.20.0/24'}
    - { port: '22' , ip_prefix: '0.0.0.0/0' }
